spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
